### ISSUE TITLE
Per group message expiry policy.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-open-group-server#35]
A feature that would be nice to have is a per group message expiry policy.

I'm not sure what it is at the moment, but I typically want to maintain message history for as long as possible in my groups.

I see that the new PySOGS code implements expiry, but it seems to be global and set at 15 days.

I would advocate a per group expiry policy; or, failing that, extension of the global policy to 30 days.

**Comment by jagerman** [comment]
> I see that the new PySOGS code implements expiry, but it seems to be global and set at 15 days.

That's only for uploaded files; messages themselves never expire.  Though there are some limitations in the current API that makes it awkward to get really old messages: Session has to download messages from the beginning of time and go forward, but can't go *backwards* from the current time.

(Edit: and also for uploaded files, room images never expire, and we have a planned feature that attachments in pinned messages will get their expiries set to unlimited).

**Comment by ianmacd** [comment]
I light of your comments, I will close this enhancement request, as its premise s invalid.
